// ============================================================
// SoA Block Stages
// Gates right-click interaction on already-placed blocks behind
// gamestages. Generated from scripts/soa_item_stages.zs with tag
// membership resolved from soa_exports/tags.json.
//
// Regenerate: python soa_additions/tools/regen_block_stages.py
// (KubeJS class filter blocks java.nio/java.io, so data is inlined.)
//
// Creative / spectator players bypass all checks.
// ============================================================

let GameStageHelper = null
try {
    GameStageHelper = Java.loadClass("net.darkhax.gamestages.GameStageHelper")
} catch (e) {
    console.error("[soa_block_stages] GameStages not found; gating disabled: " + e)
}

const ITEM_STAGES = {
    "ae2:fluix_crystal": ["nether"],
    "ae2:fluix_dust": ["nether"],
    "ae2wtlib:wireless_universal_terminal": ["graduated"],
    "aquaculture:neptunes_bounty": ["getting_started"],
    "ars_nouveau:archwood_chest": ["getting_started"],
    "ars_nouveau:archwood_planks": ["getting_started"],
    "avaritia:eternal_singularity": ["chaotic"],
    "bigreactors:cyanite_block": ["skilled_engineer"],
    "bigreactors:cyanite_ingot": ["skilled_engineer"],
    "bigreactors:yellorium_dust": ["skilled_engineer"],
    "bigreactors:yellorium_ingot": ["skilled_engineer"],
    "bloodmagic:goldsand": ["getting_started"],
    "bloodmagic:ironsand": ["getting_started"],
    "blue_skies:bluebright_chest": ["getting_started"],
    "blue_skies:bluebright_planks": ["getting_started"],
    "blue_skies:comet_chest": ["getting_started"],
    "blue_skies:comet_planks": ["getting_started"],
    "blue_skies:dusk_chest": ["getting_started"],
    "blue_skies:dusk_planks": ["getting_started"],
    "blue_skies:frostbright_chest": ["getting_started"],
    "blue_skies:frostbright_planks": ["getting_started"],
    "blue_skies:lunar_chest": ["getting_started"],
    "blue_skies:lunar_cobblestone": ["getting_started"],
    "blue_skies:lunar_planks": ["getting_started"],
    "blue_skies:maple_chest": ["getting_started"],
    "blue_skies:maple_planks": ["getting_started"],
    "blue_skies:starlit_chest": ["getting_started"],
    "blue_skies:starlit_planks": ["getting_started"],
    "blue_skies:turquoise_cobblestone": ["getting_started"],
    "botania:blaze_quartz": ["nether"],
    "botania:creative_pool": ["graduated"],
    "botania:dark_quartz": ["nether"],
    "botania:dreamwood_planks": ["getting_started"],
    "botania:elf_quartz": ["nether"],
    "botania:enchanter": ["nether"],
    "botania:framed_dreamwood": ["getting_started"],
    "botania:framed_livingwood": ["getting_started"],
    "botania:lavender_quartz": ["nether"],
    "botania:livingwood_planks": ["getting_started"],
    "botania:mana_quartz": ["nether"],
    "botania:mossy_dreamwood_planks": ["getting_started"],
    "botania:mossy_livingwood_planks": ["getting_started"],
    "botania:pattern_framed_dreamwood": ["getting_started"],
    "botania:pattern_framed_livingwood": ["getting_started"],
    "botania:red_quartz": ["nether"],
    "botania:shimmerwood_planks": ["getting_started"],
    "botania:sunny_quartz": ["nether"],
    "cataclysm:chorus_planks": ["getting_started"],
    "chancecubes:creative_pendant": ["graduated"],
    "cyclic:workbench": ["getting_started"],
    "dankstorage:dank_6": ["graduated"],
    "deeperdarker:bloom_planks": ["getting_started"],
    "deeperdarker:echo_planks": ["getting_started"],
    "draconicevolution:creative_capacitor": ["graduated"],
    "draconicevolution:deepslate_draconium_ore": ["fusion_matrix"],
    "draconicevolution:draconic_staff": ["wielder_of_infinity"],
    "draconicevolution:draconium_block": ["fusion_matrix"],
    "draconicevolution:draconium_dust": ["fusion_matrix"],
    "draconicevolution:draconium_ingot": ["fusion_matrix"],
    "draconicevolution:end_draconium_ore": ["fusion_matrix"],
    "draconicevolution:nether_draconium_ore": ["fusion_matrix"],
    "draconicevolution:overworld_draconium_ore": ["fusion_matrix"],
    "ecologics:azalea_planks": ["getting_started"],
    "ecologics:coconut_planks": ["getting_started"],
    "ecologics:flowering_azalea_planks": ["getting_started"],
    "ecologics:walnut_planks": ["getting_started"],
    "enderio:dark_steel_sword": ["novice_engineer"],
    "enderio:powdered_cobalt": ["nether"],
    "enderio:powdered_gold": ["getting_started"],
    "enderio:powdered_iron": ["getting_started"],
    "enderio:powdered_quartz": ["nether"],
    "forbidden_arcanus:arcane_edelwood_planks": ["getting_started"],
    "forbidden_arcanus:aurum_planks": ["getting_started"],
    "forbidden_arcanus:dark_nether_star": ["abyssal_conquerer"],
    "forbidden_arcanus:edelwood_planks": ["getting_started"],
    "forbidden_arcanus:fungyss_planks": ["getting_started"],
    "inventorypets:pet_cloud": ["awakened"],
    "inventorypets:pet_nether_portal": ["nether"],
    "inventorypets:pet_squid": ["nether"],
    "jaopca:dusts.cryonium": ["hardmode"],
    "jaopca:dusts.cytosinite": ["hardmode"],
    "jaopca:dusts.titanium": ["awakened"],
    "jaopca:nuggets.cryonium": ["hardmode"],
    "jaopca:nuggets.titanium": ["awakened"],
    "jaopca:storage_blocks.ethaxium": ["hardmode"],
    "jaopca:storage_blocks.meteor": ["nether"],
    "jaopca:storage_blocks.mirion": ["abyssal_conquerer"],
    "magicfeather:magic_feather": ["awakened"],
    "mekanism:dust_gold": ["getting_started"],
    "mekanism:dust_iron": ["getting_started"],
    "mekanism:dust_quartz": ["nether"],
    "minecraft:acacia_planks": ["getting_started"],
    "minecraft:anvil": ["nether"],
    "minecraft:bamboo_planks": ["getting_started"],
    "minecraft:beacon": ["nether"],
    "minecraft:birch_planks": ["getting_started"],
    "minecraft:blaze_powder": ["nether"],
    "minecraft:blaze_rod": ["nether"],
    "minecraft:brewing_stand": ["nether"],
    "minecraft:cherry_planks": ["getting_started"],
    "minecraft:chest": ["getting_started"],
    "minecraft:cobbled_deepslate": ["getting_started"],
    "minecraft:cobblestone": ["getting_started"],
    "minecraft:crafting_table": ["getting_started"],
    "minecraft:crimson_planks": ["getting_started"],
    "minecraft:dark_oak_planks": ["getting_started"],
    "minecraft:diamond_axe": ["getting_started"],
    "minecraft:diamond_boots": ["wielder_of_infinity"],
    "minecraft:diamond_chestplate": ["wielder_of_infinity"],
    "minecraft:diamond_helmet": ["wielder_of_infinity"],
    "minecraft:diamond_leggings": ["wielder_of_infinity"],
    "minecraft:diamond_pickaxe": ["wielder_of_infinity"],
    "minecraft:diamond_sword": ["wielder_of_infinity"],
    "minecraft:dragon_egg": ["hardmode"],
    "minecraft:elytra": ["hardmode"],
    "minecraft:enchanted_book": ["nether"],
    "minecraft:enchanting_table": ["nether"],
    "minecraft:end_crystal": ["wither_slayer"],
    "minecraft:end_portal_frame": ["ender_charm"],
    "minecraft:end_rod": ["ender_charm"],
    "minecraft:end_stone_bricks": ["ender_charm"],
    "minecraft:ender_chest": ["getting_started"],
    "minecraft:ender_eye": ["nether"],
    "minecraft:ghast_tear": ["nether"],
    "minecraft:glowstone": ["nether"],
    "minecraft:glowstone_dust": ["nether"],
    "minecraft:gold_block": ["getting_started"],
    "minecraft:gold_ingot": ["getting_started"],
    "minecraft:gold_nugget": ["getting_started"],
    "minecraft:golden_axe": ["getting_started"],
    "minecraft:golden_pickaxe": ["getting_started"],
    "minecraft:infested_cobblestone": ["getting_started"],
    "minecraft:iron_axe": ["getting_started"],
    "minecraft:iron_block": ["getting_started"],
    "minecraft:iron_ingot": ["getting_started"],
    "minecraft:iron_nugget": ["getting_started"],
    "minecraft:iron_pickaxe": ["getting_started"],
    "minecraft:jungle_planks": ["getting_started"],
    "minecraft:magma_cream": ["nether"],
    "minecraft:mangrove_planks": ["getting_started"],
    "minecraft:mossy_cobblestone": ["getting_started"],
    "minecraft:nether_quartz_ore": ["nether"],
    "minecraft:nether_star": ["abyssal_conquerer"],
    "minecraft:netherite_block": ["nether"],
    "minecraft:netherite_ingot": ["nether"],
    "minecraft:oak_planks": ["getting_started"],
    "minecraft:popped_chorus_fruit": ["hardmode"],
    "minecraft:quartz": ["nether"],
    "minecraft:quartz_block": ["nether"],
    "minecraft:spruce_planks": ["getting_started"],
    "minecraft:stone_axe": ["getting_started"],
    "minecraft:stone_pickaxe": ["getting_started"],
    "minecraft:trapped_chest": ["getting_started"],
    "minecraft:warped_planks": ["getting_started"],
    "minecraft:wither_skeleton_skull": ["abyssal_conquerer"],
    "minecraft:wooden_axe": ["getting_started"],
    "minecraft:wooden_pickaxe": ["getting_started"],
    "mowziesmobs:painted_acacia": ["getting_started"],
    "mysticalagradditions:creative_essence": ["graduated"],
    "mysticalagradditions:insanium_ingot": ["challenger_f"],
    "mysticalagriculture:inferium_ingot": ["challenger_a"],
    "mysticalagriculture:prudentium_ingot": ["challenger_b"],
    "mysticalagriculture:supremium_ingot": ["challenger_e"],
    "mysticalagriculture:witherproof_block": ["wither_slayer"],
    "mysticalagriculture:witherproof_glass": ["wither_slayer"],
    "projecte:alchemical_chest": ["getting_started"],
    "projecte:tome": ["graduated"],
    "projecte:watch_of_flowing_time": ["graduated"],
    "quark:acacia_chest": ["getting_started"],
    "quark:acacia_trapped_chest": ["getting_started"],
    "quark:ancient_chest": ["getting_started"],
    "quark:ancient_planks": ["getting_started"],
    "quark:ancient_trapped_chest": ["getting_started"],
    "quark:azalea_chest": ["getting_started"],
    "quark:azalea_planks": ["getting_started"],
    "quark:azalea_trapped_chest": ["getting_started"],
    "quark:bamboo_chest": ["getting_started"],
    "quark:bamboo_trapped_chest": ["getting_started"],
    "quark:birch_chest": ["getting_started"],
    "quark:birch_trapped_chest": ["getting_started"],
    "quark:blaze_lantern": ["nether"],
    "quark:blossom_chest": ["getting_started"],
    "quark:blossom_planks": ["getting_started"],
    "quark:blossom_trapped_chest": ["getting_started"],
    "quark:cherry_chest": ["getting_started"],
    "quark:cherry_trapped_chest": ["getting_started"],
    "quark:crimson_chest": ["getting_started"],
    "quark:crimson_trapped_chest": ["getting_started"],
    "quark:dark_oak_chest": ["getting_started"],
    "quark:dark_oak_trapped_chest": ["getting_started"],
    "quark:jungle_chest": ["getting_started"],
    "quark:jungle_trapped_chest": ["getting_started"],
    "quark:mangrove_chest": ["getting_started"],
    "quark:mangrove_trapped_chest": ["getting_started"],
    "quark:nether_brick_chest": ["getting_started"],
    "quark:nether_brick_trapped_chest": ["getting_started"],
    "quark:oak_chest": ["getting_started"],
    "quark:oak_trapped_chest": ["getting_started"],
    "quark:prismarine_chest": ["getting_started"],
    "quark:prismarine_trapped_chest": ["getting_started"],
    "quark:purpur_chest": ["getting_started"],
    "quark:purpur_trapped_chest": ["getting_started"],
    "quark:spruce_chest": ["getting_started"],
    "quark:spruce_trapped_chest": ["getting_started"],
    "quark:vertical_acacia_planks": ["getting_started"],
    "quark:vertical_ancient_planks": ["getting_started"],
    "quark:vertical_azalea_planks": ["getting_started"],
    "quark:vertical_bamboo_planks": ["getting_started"],
    "quark:vertical_birch_planks": ["getting_started"],
    "quark:vertical_blossom_planks": ["getting_started"],
    "quark:vertical_cherry_planks": ["getting_started"],
    "quark:vertical_crimson_planks": ["getting_started"],
    "quark:vertical_dark_oak_planks": ["getting_started"],
    "quark:vertical_jungle_planks": ["getting_started"],
    "quark:vertical_mangrove_planks": ["getting_started"],
    "quark:vertical_oak_planks": ["getting_started"],
    "quark:vertical_spruce_planks": ["getting_started"],
    "quark:vertical_warped_planks": ["getting_started"],
    "quark:warped_chest": ["getting_started"],
    "quark:warped_trapped_chest": ["getting_started"],
    "rehooked:diamond_hook": ["nether"],
    "rehooked:ender_hook": ["ender_charm"],
    "soa_additions:adaminite_ingot": ["master_wizard"],
    "soa_additions:adrenaline": ["expert"],
    "soa_additions:aeonsteel_block": ["hardmode"],
    "soa_additions:anti_entropy_matter": ["chaotic"],
    "soa_additions:aqualite_block": ["nether"],
    "soa_additions:aqualite_ore": ["nether"],
    "soa_additions:arcane_crystal_ball": ["skilled_wizard"],
    "soa_additions:astral_metal_block": ["skilled_wizard"],
    "soa_additions:awakened_eye": ["nether"],
    "soa_additions:beast_hand": ["fusion_matrix"],
    "soa_additions:blood_sigil": ["nether"],
    "soa_additions:bloody_sacrifice": ["nether"],
    "soa_additions:bound_metal_block": ["novice_wizard"],
    "soa_additions:bound_metal_dust": ["novice_wizard"],
    "soa_additions:bound_metal_ingot": ["novice_wizard"],
    "soa_additions:bound_metal_nugget": ["novice_wizard"],
    "soa_additions:bravery_certificate": ["wither_slayer"],
    "soa_additions:broken_solarium_star": ["wyvern"],
    "soa_additions:chromasteel_block": ["awakened"],
    "soa_additions:cosmilite_block": ["chaotic"],
    "soa_additions:creative_controller": ["wielder_of_infinity"],
    "soa_additions:creative_shard": ["hardmode"],
    "soa_additions:creative_soul": ["wielder_of_infinity"],
    "soa_additions:crimsonite_block": ["skilled_wizard"],
    "soa_additions:cryonium_block": ["hardmode"],
    "soa_additions:cryonium_ingot": ["hardmode"],
    "soa_additions:cryonium_ore": ["hardmode"],
    "soa_additions:cytosinite_block": ["hardmode"],
    "soa_additions:cytosinite_ingot": ["hardmode"],
    "soa_additions:cytosinite_ore": ["hardmode"],
    "soa_additions:death_coin": ["chaotic_dominator"],
    "soa_additions:difficulty_changer": ["wielder_of_infinity"],
    "soa_additions:draconic_metal_block": ["awakened"],
    "soa_additions:draconic_metal_dust": ["awakened"],
    "soa_additions:draconic_metal_ingot": ["awakened"],
    "soa_additions:draconic_metal_nugget": ["awakened"],
    "soa_additions:dragon_soul": ["hardmode"],
    "soa_additions:dreadium_ingot": ["fearless_man"],
    "soa_additions:durasteel_block": ["nether"],
    "soa_additions:electronium_block": ["fusion_matrix"],
    "soa_additions:ender_charm": ["wither_slayer"],
    "soa_additions:energy_matter_core": ["master_wizard"],
    "soa_additions:ethaxium_ingot": ["hardmode"],
    "soa_additions:experience_singularity": ["chaotic"],
    "soa_additions:fake_philosopher_stone": ["expert"],
    "soa_additions:flux_singularity": ["chaotic"],
    "soa_additions:forbidden_bible": ["hardmode"],
    "soa_additions:fusion_matrix_block": ["hardmode"],
    "soa_additions:goodie_bag": ["expert"],
    "soa_additions:greedy_medal": ["wielder_of_infinity"],
    "soa_additions:infernium_block": ["descendant_of_the_sun"],
    "soa_additions:infernium_ingot": ["descendant_of_the_sun"],
    "soa_additions:infernium_nugget": ["descendant_of_the_sun"],
    "soa_additions:infernium_ore_block": ["descendant_of_the_sun"],
    "soa_additions:infinity_block_block": ["wielder_of_infinity"],
    "soa_additions:infinity_block_block_block": ["wielder_of_infinity"],
    "soa_additions:mana_singularity": ["chaotic"],
    "soa_additions:matter_singularity": ["chaotic"],
    "soa_additions:medkit_big": ["nether"],
    "soa_additions:medkit_super": ["hardmode"],
    "soa_additions:meteor_ingot": ["nether"],
    "soa_additions:mirion_ingot": ["abyssal_conquerer"],
    "soa_additions:mithminite_ingot": ["master_wizard"],
    "soa_additions:mithrillium_ingot": ["master_wizard"],
    "soa_additions:north_star": ["abyssal_conquerer"],
    "soa_additions:ocd_certificate": ["graduated"],
    "soa_additions:ordinary_medal": ["hardmode"],
    "soa_additions:pioneer_medal": ["wielder_of_infinity"],
    "soa_additions:protonium_block": ["awakened"],
    "soa_additions:purifying_pill": ["master_wizard"],
    "soa_additions:ravaging_ingot": ["nether"],
    "soa_additions:remorseful_gem": ["nether"],
    "soa_additions:sentient_metal_block": ["novice_wizard"],
    "soa_additions:sentient_metal_dust": ["novice_wizard"],
    "soa_additions:sentient_metal_ingot": ["novice_wizard"],
    "soa_additions:sentient_metal_nugget": ["novice_wizard"],
    "soa_additions:shield_gum": ["expert"],
    "soa_additions:shining_star": ["nether"],
    "soa_additions:solar_seed": ["wyvern"],
    "soa_additions:solarium_star": ["wyvern"],
    "soa_additions:strange_lolipop": ["expert"],
    "soa_additions:sun_totem": ["wyvern"],
    "soa_additions:terra_alloy_block": ["awakened"],
    "soa_additions:titanium_block": ["awakened"],
    "soa_additions:titanium_ingot": ["awakened"],
    "soa_additions:titanium_ore": ["awakened"],
    "soa_additions:true_blood_sigil": ["hardmode"],
    "soa_additions:undead_medkit": ["expert"],
    "soa_additions:wither_soul": ["hardmode"],
    "soa_additions:yellorium_ingot": ["skilled_engineer"],
    "solarflux:sp_5": ["skilled_engineer"],
    "solarflux:sp_6": ["skilled_engineer"],
    "solarflux:sp_7": ["skilled_engineer"],
    "solarflux:sp_8": ["master_engineer"],
    "solarflux:sp_avaritia.infinity": ["wielder_of_infinity"],
    "solarflux:sp_avaritia.neutronium": ["master_engineer"],
    "solarflux:sp_de.chaotic": ["master_engineer"],
    "solarflux:sp_de.draconic": ["master_engineer"],
    "solarflux:sp_de.wyvern": ["master_engineer"],
    "storagedrawers:creative_storage_upgrade": ["graduated"],
    "tconstruct:bloodshroom_planks": ["getting_started"],
    "tconstruct:cobalt_ingot": ["nether"],
    "tconstruct:cobalt_ore": ["nether"],
    "tconstruct:crafting_station": ["getting_started"],
    "tconstruct:enderbark_planks": ["getting_started"],
    "tconstruct:greenheart_planks": ["getting_started"],
    "tconstruct:part_builder": ["getting_started"],
    "tconstruct:part_chest": ["getting_started"],
    "tconstruct:rod_cast": ["awakened"],
    "tconstruct:skyroot_planks": ["getting_started"],
    "tconstruct:tinkers_anvil": ["getting_started"],
    "tconstruct:tinkers_chest": ["getting_started"],
    "tconstruct:tinkers_gadgetry": ["getting_started"],
    "thaumon:greatwood_planks": ["getting_started"],
    "thaumon:silverwood_planks": ["getting_started"],
    "thermal:deepslate_ruby_ore": ["hardmode"],
    "thermal:deepslate_sapphire_ore": ["hardmode"],
    "thermal:enderium_block": ["skilled_engineer"],
    "thermal:enderium_dust": ["skilled_engineer"],
    "thermal:enderium_gear": ["skilled_engineer"],
    "thermal:enderium_ingot": ["skilled_engineer"],
    "thermal:enderium_nugget": ["skilled_engineer"],
    "thermal:gold_dust": ["getting_started"],
    "thermal:iron_dust": ["getting_started"],
    "thermal:lumium_block": ["nether"],
    "thermal:lumium_dust": ["nether"],
    "thermal:lumium_gear": ["nether"],
    "thermal:lumium_ingot": ["nether"],
    "thermal:lumium_nugget": ["nether"],
    "thermal:quartz_dust": ["nether"],
    "thermal:rubberwood_planks": ["getting_started"],
    "thermal:ruby_ore": ["hardmode"],
    "thermal:sapphire_ore": ["hardmode"],
    "thermal:watering_can": ["graduated"],
    "tinymobfarm:diamond_farm": ["challenger_d"],
    "tinymobfarm:emerald_farm": ["challenger_e"],
    "tinymobfarm:gold_farm": ["challenger_c"],
    "tinymobfarm:inferno_farm": ["challenger_f"],
    "tinymobfarm:iron_farm": ["challenger_b"],
    "tinymobfarm:stone_farm": ["challenger_a"],
    "tinymobfarm:ultimate_farm": ["challenger_g"],
    "treasure2:skull_sword": ["nether"],
    "twilightforest:canopy_chest": ["getting_started"],
    "twilightforest:canopy_planks": ["getting_started"],
    "twilightforest:cracked_towerwood": ["getting_started"],
    "twilightforest:dark_chest": ["getting_started"],
    "twilightforest:dark_planks": ["getting_started"],
    "twilightforest:encased_towerwood": ["getting_started"],
    "twilightforest:fortification_scepter": ["hardmode"],
    "twilightforest:infested_towerwood": ["getting_started"],
    "twilightforest:mangrove_chest": ["getting_started"],
    "twilightforest:mangrove_planks": ["getting_started"],
    "twilightforest:mining_chest": ["getting_started"],
    "twilightforest:mining_planks": ["getting_started"],
    "twilightforest:mossy_towerwood": ["getting_started"],
    "twilightforest:sorting_chest": ["getting_started"],
    "twilightforest:sorting_planks": ["getting_started"],
    "twilightforest:time_chest": ["getting_started"],
    "twilightforest:time_planks": ["getting_started"],
    "twilightforest:towerwood": ["getting_started"],
    "twilightforest:transformation_chest": ["getting_started"],
    "twilightforest:transformation_planks": ["getting_started"],
    "twilightforest:twilight_oak_chest": ["getting_started"],
    "twilightforest:twilight_oak_planks": ["getting_started"],
    "upgrade_aquatic:driftwood_chest": ["getting_started"],
    "upgrade_aquatic:driftwood_planks": ["getting_started"],
    "upgrade_aquatic:river_chest": ["getting_started"],
    "upgrade_aquatic:river_planks": ["getting_started"],
    "upgrade_aquatic:trapped_driftwood_chest": ["getting_started"],
    "upgrade_aquatic:trapped_river_chest": ["getting_started"]
}

console.info("[soa_block_stages] loaded " + Object.keys(ITEM_STAGES).length + " item rules")

function missingStage(player, itemId) {
    if (!GameStageHelper) return null
    const rules = ITEM_STAGES[itemId]
    if (!rules) return null
    for (let i = 0; i < rules.length; i++) {
        if (!GameStageHelper.hasStage(player, rules[i])) return rules[i]
    }
    return null
}

BlockEvents.rightClicked(event => {
    const player = event.player
    if (!player) return
    if (player.isCreative() || player.isSpectator()) return

    const block = event.block
    if (!block) return
    const itemId = String(block.id)
    if (itemId === "minecraft:air") return

    const stage = missingStage(player, itemId)
    if (stage === null) return

    event.cancel()
    player.tell(Text.red("You lack the required stage: " + stage))
})
