StartupEvents.registry('fluid', event => {
    event.create('molten_andesite')
        .displayName('Molten Andesite')
        .stillTexture('tconstruct:block/fluid/molten/still')
        .flowingTexture('tconstruct:block/fluid/molten/flowing')
        .thickTexture(0x8C8C8C)
        .bucketColor(0x8C8C8C)
        .luminosity(8)
        .temperature(850)

    event.create('molten_andesite_alloy')
        .displayName('Molten Andesite Alloy')
        .stillTexture('tconstruct:block/fluid/molten/still')
        .flowingTexture('tconstruct:block/fluid/molten/flowing')
        .thickTexture(0x858585)
        .bucketColor(0x858585)
        .luminosity(8)
        .temperature(950)
})
