#This file stores configuration options for Iris, such as the currently active shaderpack
#Tue Jul 14 11:16:01 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=SoA_Radiance
enableShaders=true
