#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Aug 05 10:42:08 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=SoA_Radiance
enableShaders=true
