#This file stores configuration options for Iris, such as the currently active shaderpack
#Wed Apr 15 16:58:39 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=32
shaderPack=SoA_Radiance
enableShaders=true
