Ponder.registry((event) => {
    event.create('forbidden_arcanus:hephaestus_forge')
        .scene('hephaestus_forge_creation', 'Hephaestus Forge — Building it (Tier 1)', (scene, util) => {
            scene.configureBasePlate(0, 0, 9)
            scene.scaleSceneView(0.62)
            scene.showBasePlate()
            scene.idle(10)
            scene.world.setBlock([3, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 1], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 3], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([2, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([4, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([6, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([8, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 5], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 7], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 2, 4], 'minecraft:smithing_table', false)
            scene.world.showSection(util.select.fromTo(0, 1, 0, 8, 1, 8), Facing.DOWN)
            scene.idle(12)
            scene.world.showSection(util.select.position(4, 2, 4), Facing.DOWN)
            scene.text(70, 'Build the 9x9 ritual platform: Polished Darkstone paths, Arcane Chiseled Polished Darkstone on the eight pedestal marks, a Chiseled cross around the center, and a Smithing Table on the center mark.', [4, 2, 4])
            scene.idle(80)
            scene.text(60, 'Use Mundabitur Dust on the Smithing Table to transform it into the Hephaestus Forge (Tier 1).', [4, 2, 4])
            scene.idle(30)
            scene.world.setBlock([4, 2, 4], 'forbidden_arcanus:hephaestus_forge', false)
            scene.idle(40)
            scene.world.setBlock([4, 2, 1], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([1, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([7, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([4, 2, 7], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.showSection(util.select.fromTo(0, 2, 0, 8, 2, 8).substract(util.select.position(4, 2, 4)), Facing.DOWN)
            scene.text(70, 'Place Darkstone Pedestals on the eight arcane marks - ritual ingredients go on these. Feed essences (Aureal bottles, blood, XP, souls) into the forge.', [1, 2, 4])
            scene.idle(80)
        })
    event.create('forbidden_arcanus:hephaestus_forge')
        .scene('hephaestus_forge_tier_2', 'Hephaestus Forge — Upgrading to Tier 2', (scene, util) => {
            scene.configureBasePlate(0, 0, 9)
            scene.scaleSceneView(0.62)
            scene.showBasePlate()
            scene.idle(10)
            scene.world.setBlock([3, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 1], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 3], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([2, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([4, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([6, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([8, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 5], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 7], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 2, 4], 'forbidden_arcanus:hephaestus_forge', false)
            scene.world.setBlock([4, 2, 1], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([1, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([7, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([4, 2, 7], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.showSection(util.select.fromTo(0, 1, 0, 8, 2, 8), Facing.DOWN)
            scene.idle(15)
            scene.text(80, 'Upgrade ritual to Tier 2: Edelwood Planks (main) + 4x Arcane Crystal + 4x Spawner Scrap on the pedestals.', [4, 2, 4])
            scene.idle(90)
            scene.text(70, 'Essences required: 500 Aureal, 6000 Blood, 10 Souls.', [4, 2, 4])
            scene.idle(80)
            scene.text(70, 'Tier 2 expands the essence pool for costlier rituals.', [4, 2, 4])
            scene.idle(80)
        })
    event.create('forbidden_arcanus:hephaestus_forge')
        .scene('hephaestus_forge_tier_3', 'Hephaestus Forge — Upgrading to Tier 3', (scene, util) => {
            scene.configureBasePlate(0, 0, 9)
            scene.scaleSceneView(0.62)
            scene.showBasePlate()
            scene.idle(10)
            scene.world.setBlock([3, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 1], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 3], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([2, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([4, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([6, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([8, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 5], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 7], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 2, 4], 'forbidden_arcanus:hephaestus_forge', false)
            scene.world.setBlock([4, 2, 1], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([1, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([7, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([4, 2, 7], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.showSection(util.select.fromTo(0, 1, 0, 8, 2, 8), Facing.DOWN)
            scene.idle(15)
            scene.text(80, 'Upgrade ritual to Tier 3: Chiseled Polished Darkstone (main) + 4x Arcane Crystal + 4x Deorum Ingot on the pedestals.', [4, 2, 4])
            scene.idle(90)
            scene.text(70, 'Essences required: 1000 Aureal, 9000 Blood, 50 Souls.', [4, 2, 4])
            scene.idle(80)
            scene.text(70, 'Tier 3 expands the essence pool for costlier rituals.', [4, 2, 4])
            scene.idle(80)
        })
    event.create('forbidden_arcanus:hephaestus_forge')
        .scene('hephaestus_forge_tier_4', 'Hephaestus Forge — Upgrading to Tier 4', (scene, util) => {
            scene.configureBasePlate(0, 0, 9)
            scene.scaleSceneView(0.62)
            scene.showBasePlate()
            scene.idle(10)
            scene.world.setBlock([3, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 1], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 3], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([2, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([4, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([6, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([8, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 5], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 7], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 2, 4], 'forbidden_arcanus:hephaestus_forge', false)
            scene.world.setBlock([4, 2, 1], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([1, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([7, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([4, 2, 7], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.showSection(util.select.fromTo(0, 1, 0, 8, 2, 8), Facing.DOWN)
            scene.idle(15)
            scene.text(80, 'Upgrade ritual to Tier 4: Chiseled Polished Darkstone (main) + 4x Stellarite Piece + 4x Rune on the pedestals.', [4, 2, 4])
            scene.idle(90)
            scene.text(70, 'Essences required: 2000 Aureal, 12000 Blood, 100 Souls.', [4, 2, 4])
            scene.idle(80)
            scene.text(70, 'Tier 4 unlocks: Astral Metal ritual (fusion matrix + starmetal-iron, meteor ingots, fallen stars).', [4, 2, 4])
            scene.idle(80)
        })
    event.create('forbidden_arcanus:hephaestus_forge')
        .scene('hephaestus_forge_tier_5', 'Hephaestus Forge — Upgrading to Tier 5', (scene, util) => {
            scene.configureBasePlate(0, 0, 9)
            scene.scaleSceneView(0.62)
            scene.showBasePlate()
            scene.idle(10)
            scene.world.setBlock([3, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 0], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 1], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 1], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 2], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 2], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 3], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 3], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([2, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([4, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 4], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([6, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 4], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([8, 1, 4], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([0, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 5], 'forbidden_arcanus:chiseled_arcane_polished_darkstone', false)
            scene.world.setBlock([5, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([8, 1, 5], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([3, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 6], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([7, 1, 6], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([1, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([2, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 7], 'forbidden_arcanus:arcane_chiseled_polished_darkstone', false)
            scene.world.setBlock([5, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([6, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([7, 1, 7], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([3, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([5, 1, 8], 'forbidden_arcanus:polished_darkstone', false)
            scene.world.setBlock([4, 2, 4], 'forbidden_arcanus:hephaestus_forge', false)
            scene.world.setBlock([4, 2, 1], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 2], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([1, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([7, 2, 4], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([2, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([6, 2, 6], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.setBlock([4, 2, 7], 'forbidden_arcanus:darkstone_pedestal', false)
            scene.world.showSection(util.select.fromTo(0, 1, 0, 8, 2, 8), Facing.DOWN)
            scene.idle(15)
            scene.text(80, 'Upgrade ritual to Tier 5: Stellarite Block (main) + 4x Sculk Catalyst + 2x Dark Nether Star + 2x Dragon Scale on the pedestals.', [4, 2, 4])
            scene.idle(90)
            scene.text(70, 'Essences required: 5000 Aureal, 20000 Blood, 500 Souls.', [4, 2, 4])
            scene.idle(80)
            scene.text(70, 'Tier 5 unlocks the Thaumic metal rituals: Mithrillium, Adaminite and Mithminite.', [4, 2, 4])
            scene.idle(80)
        })
})
