ServerEvents.recipes(event => {
    event.custom({ type: 'avaritia:shaped_table', pattern: ["         ", "         ", "         ", "         ", "ABCCCCCBA", "ABCCCCCBA", "ABCCCCCBA", "ABBBBBBBA", "AAAAAAAAA"], key: {"A": {"item": "botania:livingrock"}, "B": {"item": "botania:terrasteel_ingot"}, "C": {"item": "soa_additions:creative_soul"}}, result: { item: 'botania:creative_pool', count: 1 } }).id('soa_parity:custom_avaritia_recipe_22')
    event.custom({ type: 'avaritia:shaped_table', pattern: ["         ", " A    A  ", "    A    ", "   AAA   ", "  AABAA  ", "  AAAAA  ", "   AAA   ", "         ", "         "], key: {"A": {"item": "soa_additions:creative_shard"}, "B": {"item": "mysticalagradditions:insanium_essence"}}, result: { item: 'mysticalagradditions:creative_essence', count: 1 } }).id('soa_parity:custom_avaritia_recipe_23')
    event.custom({ type: 'avaritia:shaped_table', pattern: ["         ", "         ", "   ABA   ", "  ABBBA  ", "  BCDCB  ", "  ABBBA  ", "   ABA   ", "         ", "         "], key: {"A": {"item": "projecte:klein_star_omega"}, "B": {"item": "soa_additions:creative_soul"}, "C": {"item": "soa_additions:infinity_block_block"}, "D": {"item": "minecraft:clock"}}, result: { item: 'projecte:watch_of_flowing_time', count: 1 } }).id('soa_parity:custom_avaritia_recipe_27')
    event.custom({ type: 'avaritia:shaped_table', pattern: ["AAAAAAAAA", "ABBBBBBBA", "ABBBBBBBA", "ABBBBBBBA", "AAAACAAAA", "ADDDDDDDA", "ADDDDDDDA", "ADDDDDDDA", "AAAAAAAAA"], key: {"A": {"item": "soa_additions:creative_soul"}, "B": {"item": "storagedrawers:emerald_storage_upgrade"}, "C": {"item": "soa_additions:infinity_block_block"}, "D": {"item": "storagedrawers:creative_storage_upgrade"}}, result: { item: 'storagedrawers:creative_vending_upgrade', count: 1 } }).id('soa_parity:custom_avaritia_recipe_39')

    event.shapeless(Item.of('minecraft:skeleton_skull', 1), ['minecraft:name_tag', 'minecraft:skeleton_skull']).id('soa_parity:nametag_to_head')
    event.shaped(Item.of('simplybackpacks:commonbackpack', 1), ["A A", "BCB", "BDB"], {A: '#forge:string', B: '#forge:leather', C: '#forge:ingots/iron', D: '#forge:chests'}).id('soa_parity:backpack_func_0')
    event.shaped(Item.of('projecte:harvest_goddess_band', 1), ["ABA", "BCB", "ABA"], {A: 'soa_additions:creative_soul', B: 'minecraft:vine', C: 'projecte:iron_band'}).id('soa_parity:auto_gen_1124990531')
    event.shaped(Item.of('projecte:nova_catalyst', 1), ["AAA", "BCB", "AAA"], {A: 'projecte:mobius_fuel', B: 'projecte:red_matter', C: 'minecraft:tnt'}).id('soa_parity:auto_gen__132199471')
    event.shaped(Item.of('projecte:nova_cataclysm', 1), ["AAA", "AAA", "AAA"], {A: 'projecte:nova_catalyst'}).id('soa_parity:auto_gen_1281372914')
    event.shaped(Item.of('mysticalagriculture:inferium_growth_accelerator', 2), ["ABA", "BCB", "ABA"], {A: 'mysticalagriculture:supremium_block', B: 'mysticalagradditions:insanium_block', C: '#forge:storage_blocks/cytosinite'}).id('soa_parity:auto_gen_1179581625')
    event.shaped(Item.of('mekanismgenerators:turbine_vent', 1), [" A ", "ABA", " A "], {A: 'mekanismgenerators:turbine_casing', B: 'soa_additions:creative_soul'}).id('soa_parity:auto_gen__1186141268')
    event.shaped(Item.of('mekanism:digital_miner', 1), ["ABA", "CDE", "FGF"], {A: 'mekanism:teleportation_core', B: 'mekanism:logistical_sorter', C: 'mekanism:robit', D: 'mekanism:steel_casing', E: 'mekanism:chemical_dissolution_chamber', F: 'soa_additions:creative_shard', G: '#forge:storage_blocks/wyvern_metal'}).id('soa_parity:auto_gen__1864302722')
    event.shaped(Item.of('mekanismgenerators:wind_generator', 1), [" A ", "ABA", "CDC"], {A: 'mekanism:alloy_atomic', B: '#forge:ingots/aeonsteel', C: 'mekanism:energy_tablet', D: 'mekanism:ultimate_control_circuit'}).id('soa_parity:auto_gen_1084804943')
    event.shaped(Item.of('mekanismgenerators:advanced_solar_generator', 1), ["AAA", "ABA", "CCC"], {A: 'mekanismgenerators:solar_generator', B: 'mekanism:alloy_atomic', C: 'mekanism:alloy_infused'}).id('soa_parity:auto_gen_685141373')
    event.shaped(Item.of('projecte:soul_stone', 1), ["ABA", "CDC", "ABA"], {A: 'minecraft:gold_ingot', B: 'draconicevolution:awakened_core', C: 'botania:mana_diamond_block', D: 'soa_additions:creative_shard'}).id('soa_parity:auto_gen__1399323772')
    event.shaped(Item.of('projecte:body_stone', 1), ["AAA", "BCB", "AAA"], {A: 'minecraft:gold_ingot', B: 'soa_additions:creative_shard', C: 'draconicevolution:chaotic_core'}).id('soa_parity:auto_gen__1815095390')

    event.shaped(Item.of('ironchest:diamond_chest', 1), ["AAA", "BCB", "AAA"], {A: 'minecraft:glass', B: 'minecraft:diamond', C: 'minecraft:gold_block'}).id('soa_parity:auto_gen_893026726')
    event.shaped(Item.of('projecte:interdiction_torch', 1), [" A ", "BCB", "DDD"], {A: 'soa_additions:creative_shard', B: 'projecte:red_matter', C: 'minecraft:torch', D: 'minecraft:glowstone_dust'}).id('soa_parity:auto_gen__626897020')
    event.shaped(Item.of('valoria:iron_ring', 1), ["AAA", "A A", "AAA"], {A: '#forge:nuggets/iron'}).id('soa_parity:auto_gen__378684063')
    event.shaped(Item.of('draconicevolution:grinder', 1), ["ABA", "BCB", "ABA"], {A: 'minecraft:iron_block', B: 'draconicevolution:awakened_core', C: 'tconevo:chaotic_block'}).id('soa_parity:auto_gen__893381298')
    event.shaped(Item.of('cyclic:wireless_item', 1), ["ABA", "BCB", "ABA"], {A: 'thermal:enderium_ingot', B: 'minecraft:ender_eye', C: 'minecraft:chest'}).id('soa_parity:auto_gen__1542308372')
    event.shaped(Item.of('cyclic:wireless_energy', 1), ["ABA", "BCB", "ABA"], {A: 'thermal:enderium_ingot', B: 'minecraft:ender_eye', C: 'minecraft:redstone_block'}).id('soa_parity:auto_gen_142121176')
    event.shaped(Item.of('cyclic:wireless_fluid', 1), ["ABA", "BCB", "ABA"], {A: 'thermal:enderium_ingot', B: 'minecraft:ender_eye', C: 'minecraft:bucket'}).id('soa_parity:auto_gen__1750189736')
    event.shaped(Item.of('projecte:swiftwolf_rending_gale', 1), ["ABA", "CDC", "ABA"], {A: '#forge:feathers', B: 'soa_additions:creative_shard', C: 'magicfeather:magic_feather', D: 'projecte:iron_band'}).id('soa_parity:auto_gen__1836563570')
    event.shaped(Item.of('ae2:cell_component_1k', 4), [" A ", "ABA", " A "], {A: '#forge:dusts/redstone', B: '#forge:gems/quartz'}).id('soa_parity:auto_gen__555162558')
    event.shaped(Item.of('tiab:time_in_a_bottle', 1), ["ABA", "BCB", "ABA"], {A: 'soa_additions:creative_shard', B: 'draconicevolution:awakened_core', C: 'minecraft:glass_bottle'}).id('soa_parity:auto_gen__627290965')
    event.shaped(Item.of('cyclic:slingshot', 1), ["ABA", " A ", " A "], {A: '#forge:rods/wooden', B: '#forge:string'}).id('soa_parity:auto_gen__1848316431')
    event.shaped(Item.of('summoningrituals:altar', 1), ["ABA", "BCB", "ABA"], {A: 'minecraft:ender_eye', B: 'tconevo:coalescence_matrix', C: '#forge:nether_stars'}).id('soa_parity:auto_gen__14951606')
    event.shaped(Item.of('thermal:machine_frame', 1), ["ABA", "BCB", "ABA"], {A: '#forge:glass', B: '#forge:ingots/iron', C: '#forge:gears/tin'}).id('soa_parity:frame_alt')
    event.shaped(Item.of('solarflux:sp_2', 1), ["AAA", "BCB", "DDD"], {A: 'solarflux:mirror', B: 'solarflux:sp_1', C: '#forge:ingots/gold', D: '#forge:ingots/iron'}).id('soa_parity:sol_flux_panel_1')
    event.shaped(Item.of('solarflux:sp_3', 1), ["AAA", "BCB", "BBB"], {A: 'solarflux:photovoltaic_cell_1', B: '#forge:ingots/invar', C: 'solarflux:sp_2'}).id('soa_parity:sol_flux_panel_2')
    event.shaped(Item.of('solarflux:sp_4', 1), ["AAA", "BCB", "BBB"], {A: 'solarflux:photovoltaic_cell_2', B: '#forge:ingots/steel', C: 'solarflux:sp_3'}).id('soa_parity:sol_flux_panel_3')
    event.shaped(Item.of('solarflux:sp_5', 1), ["AAA", "BCB", "BDB"], {A: 'solarflux:photovoltaic_cell_3', B: '#forge:ingots/stainless_steel', C: 'solarflux:sp_4', D: '#forge:ingots/energetic_alloy'}).id('soa_parity:sol_flux_panel_4')
    event.shaped(Item.of('solarflux:sp_8', 1), ["AAA", "BCB", "BBB"], {A: 'solarflux:photovoltaic_cell_6', B: '#forge:ingots/aeonsteel', C: 'solarflux:sp_7'}).id('soa_parity:sol_flux_panel_7')
    event.shaped(Item.of('minecraft:netherite_block', 1), ["AAA", "AAA", "AAA"], {A: '#forge:ingots/netherite'}).id('soa_parity:netherite_block')
    event.shaped(Item.of('mekanism:steel_casing', 1), ["ABA", "BCB", "ABA"], {A: '#forge:ingots/stainless_steel', B: 'thermal:obsidian_glass', C: '#forge:ingots/osmium'}).id('soa_parity:mekanism_casing')
    event.shaped(Item.of('buildinggadgets2:gadget_building', 1), ["ABA", "CDC", "ABA"], {A: '#forge:ingots/stainless_steel', B: '#forge:dusts/redstone', C: '#forge:ingots/bronze', D: '#forge:gems/diamond'}).id('soa_parity:auto_gen_2008269634')
    event.shaped(Item.of('buildinggadgets2:gadget_exchanging', 1), ["ABA", "CDC", "ABA"], {A: '#forge:ingots/stainless_steel', B: '#forge:dusts/redstone', C: 'minecraft:ender_eye', D: '#forge:gems/diamond'}).id('soa_parity:auto_gen_352019415')
    event.shaped(Item.of('buildinggadgets2:gadget_copy_paste', 1), ["ABA", "CDC", "ABA"], {A: '#forge:ingots/stainless_steel', B: '#forge:dusts/redstone', C: '#forge:slimeballs', D: '#forge:gems/diamond'}).id('soa_parity:auto_gen__1071431898')
    event.shaped(Item.of('buildinggadgets2:gadget_destruction', 1), ["ABA", "CDC", "ABA"], {A: '#forge:ingots/aeonsteel', B: 'minecraft:bedrock', C: '#forge:ingots/ravaging', D: '#forge:nether_stars'}).id('soa_parity:auto_gen_12241914')
    event.shaped(Item.of('cyclic:harvester', 1), [" A ", "BCB", "DBD"], {A: 'cyclic:scythe_harvest', B: '#forge:ingots/aeonsteel', C: 'minecraft:dispenser', D: 'mekanism:ultimate_control_circuit'}).id('soa_parity:harvester')
    event.shaped(Item.of('bloodmagic:soulforge', 1), ["A A", "BCB", "BDB"], {A: '#forge:ingots/stainless_steel', B: '#forge:storage_blocks/nether_brick', C: '#forge:rods/blaze', D: '#forge:storage_blocks/iron'}).id('soa_parity:soul_forge')
    event.shaped(Item.of('thaumon:amber_bricks', 4), ["AA", "AA"], {A: 'valoria:amber_block'}).id('soa_parity:amber_brick')
    event.shaped(Item.of('cyclic:heart', 1), ["AAA", "ABA", "AAA"], {A: 'cyclic:heart', B: '#forge:ingots/crimsonite'}).id('soa_parity:cyclic_heart_food')
    event.shaped(Item.of('rehooked:ender_hook', 1), ["ABC", " DB", "E A"], {A: 'minecraft:ender_eye', B: '#forge:rods/blaze', C: 'minecraft:end_stone', D: 'rehooked:ender_hook', E: 'minecraft:blaze_powder'}).id('soa_parity:ender_hook')
    event.shaped(Item.of('aether:ice_ring', 1), ["ABA", "B B", "ABA"], {A: 'minecraft:ice', B: '#forge:ingots/asgardium'}).id('soa_parity:ice_ring')
    event.shaped(Item.of('aether:zanite_ring', 1), ["ABA", "B B", "ABA"], {A: 'aether:zanite_gemstone', B: '#forge:ingots/asgardium'}).id('soa_parity:zanite_ring')
    event.shaped(Item.of('thermal:iron_plate', 4), ["AA", "AA"], {A: '#forge:ingots/iron'}).id('soa_parity:iron_plate')
    event.shaped(Item.of('minecraft:iron_trapdoor', 2), ["AAA", "ABA", "AAA"], {A: '#forge:ingots/iron', B: '#forge:dusts/redstone'}).id('soa_parity:iron_trap_door')
    event.shaped(Item.of('mekanismgenerators:turbine_casing', 16), ["ABA", "BCB", "ABA"], {A: '#forge:ingots/titanium', B: '#forge:ingots/aeonsteel', C: 'soa_additions:creative_shard'}).id('soa_parity:turbo_casing')
    event.shaped(Item.of('mekanism:boiler_casing', 1), [" A ", "ABA", " A "], {A: '#forge:ingots/aeonsteel', B: '#forge:ingots/stainless_steel'}).id('soa_parity:mek_casing_2')
    event.shaped(Item.of('mekanism:advanced_control_circuit', 1), [" A ", "BCB", " A "], {A: '#forge:ingots/stainless_steel', B: 'mekanism:alloy_infused', C: 'mekanism:basic_control_circuit'}).id('soa_parity:mek_circuit_1')
    event.shaped(Item.of('mekanism:elite_control_circuit', 1), [" A ", "BCB", " A "], {A: '#forge:ingots/durasteel', B: 'mekanism:alloy_reinforced', C: 'mekanism:advanced_control_circuit'}).id('soa_parity:mek_circuit_2')
    event.shaped(Item.of('mekanism:ultimate_control_circuit', 1), [" A ", "BCB", " A "], {A: '#forge:ingots/aeonsteel', B: 'mekanism:alloy_atomic', C: 'mekanism:elite_control_circuit'}).id('soa_parity:mek_circuit_3')
    event.shaped(Item.of('torchmaster:megatorch', 1), ["ABA", "CDC", "EDE"], {A: '#forge:slimeballs', B: 'minecraft:torch', C: '#forge:gems/diamond', D: '#minecraft:planks', E: '#forge:ingots/gold'}).id('soa_parity:mega_torch')
    event.shaped(Item.of('torchmaster:feral_flare_lantern', 1), ["ABA", "CDC", "ADA"], {A: '#forge:glass', B: 'minecraft:blaze_powder', C: '#forge:slimeballs', D: '#forge:rods/blaze'}).id('soa_parity:flare_lantern')
    event.shaped(Item.of('torchmaster:dreadlamp', 1), ["ABA", "CDC", "ABA"], {A: '#forge:obsidian', B: '#forge:glass', C: '#forge:slimeballs', D: '#forge:rods/blaze'}).id('soa_parity:dread_lamp')
    event.shapeless(Item.of('scalinghealth:heart_dust', 9), ['scalinghealth:heart_crystal_shard']).id('soa_parity:auto_gen_1565439995')

    event.shapeless(Item.of('mysticalagriculture:prudentium_essence', 1), ['mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence']).id('soa_parity:ma_essence_0')
    event.shapeless(Item.of('mysticalagriculture:supremium_essence', 1), ['mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence']).id('soa_parity:ma_essence_3')
    event.shapeless(Item.of('mysticalagriculture:inferium_ingot', 1), ['mysticalagriculture:prosperity_ingot', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence', 'mysticalagriculture:inferium_essence']).id('soa_parity:auto_gen_271729765')
    event.shapeless(Item.of('mysticalagriculture:prudentium_ingot', 1), ['mysticalagriculture:prosperity_ingot', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence', 'mysticalagriculture:prudentium_essence']).id('soa_parity:auto_gen_2055027330')
    event.shapeless(Item.of('mysticalagriculture:supremium_ingot', 1), ['mysticalagriculture:prosperity_ingot', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence', 'mysticalagriculture:supremium_essence']).id('soa_parity:auto_gen_1800275409')
    event.shapeless(Item.of('mysticalagradditions:insanium_ingot', 1), ['mysticalagriculture:prosperity_ingot', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence', 'mysticalagradditions:insanium_essence']).id('soa_parity:auto_gen__1248999641')
    event.shapeless(Item.of('minecraft:experience_bottle', 1), ['minecraft:glass_bottle', 'actuallyadditions:empowered_palis_crystal']).id('soa_parity:auto_gen__628920196')
    event.shapeless(Item.of('storagedrawers:creative_storage_upgrade', 32), ['storagedrawers:upgrade_template', 'draconicevolution:awakened_core']).id('soa_parity:auto_gen__2041446050')
    event.shapeless(Item.of('ae2:cell_component_4k', 1), ['ae2:cell_component_1k', 'ae2:cell_component_1k', 'ae2:cell_component_1k', 'ae2:cell_component_1k']).id('soa_parity:auto_gen__1028255111')
    event.shapeless(Item.of('ae2:cell_component_16k', 1), ['ae2:cell_component_4k', 'ae2:cell_component_4k', 'ae2:cell_component_4k', 'ae2:cell_component_4k']).id('soa_parity:auto_gen__1168410344')
    event.shapeless(Item.of('patchouli:guide_book', 1), ['#forge:rods/wooden', '#forge:rods/wooden', '#forge:rods/wooden']).id('soa_parity:pack_guide_book')
    event.shapeless(Item.of('enderzoology:withering_dust', 1), ['supplementaries:ash']).id('soa_parity:auto_gen_2033568330')
    event.shapeless(Item.of('treasure2:ruby_key', 1), ['#forge:dusts/glowstone', 'treasure2:gold_key', 'treasure2:treasure_tool', '#forge:gems/ruby']).id('soa_parity:red_key')
    event.shapeless(Item.of('treasure2:sapphire_key', 1), ['#forge:dusts/glowstone', 'treasure2:gold_key', 'treasure2:treasure_tool', '#forge:gems/sapphire']).id('soa_parity:blue_key')
    event.shapeless(Item.of('avaritia:neutron_ingot', 2), ['#forge:ingots/protonium', '#forge:ingots/electronium']).id('soa_parity:neutronium_combination')
    event.shapeless(Item.of('avaritia:neutron', 2), ['#forge:storage_blocks/protonium', '#forge:storage_blocks/electronium']).id('soa_parity:neutronium_block_combination')

    event.remove({ output: 'bloodmagic:reagentbinding', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'bloodmagic:reagentbinding', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'minecraft:coal', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'minecraft:coal', type: 'minecraft:crafting_shapeless' })

    event.remove({ output: 'chancecubes:creative_pendant', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'chancecubes:creative_pendant', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'mysticalagradditions:creative_essence', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'mysticalagradditions:creative_essence', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'soa_additions:creative_controller', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'soa_additions:creative_controller', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'storagedrawers:creative_vending_upgrade', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'storagedrawers:creative_vending_upgrade', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'soa_additions:difficulty_changer', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'soa_additions:difficulty_changer', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'draconicevolution:draconic_staff', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'draconicevolution:draconic_staff', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'avaritia:eternal_singularity', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'avaritia:eternal_singularity', type: 'minecraft:crafting_shapeless', not: { id: 'soa_ported:gc_adds/eternal_singularity_dupe' } })
    event.remove({ output: 'soa_additions:gaiasteel_ingot', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'soa_additions:gaiasteel_ingot', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'avaritia:infinity_catalyst', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'avaritia:infinity_catalyst', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'botania:livingwood', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'botania:livingwood', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'soa_additions:passport', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'soa_additions:passport', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'mekanism:dust_steel', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'mekanism:dust_steel', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'mekanism:ingot_steel', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'mekanism:ingot_steel', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'tconstruct:steel_ingot', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'tconstruct:steel_ingot', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'avaritia:infinity_sword', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'avaritia:infinity_sword', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'botania:creative_pool', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'botania:creative_pool', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'projecte:tome', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'projecte:tome', type: 'minecraft:crafting_shapeless' })
    event.remove({ output: 'projecte:watch_of_flowing_time', type: 'minecraft:crafting_shaped' })
    event.remove({ output: 'projecte:watch_of_flowing_time', type: 'minecraft:crafting_shapeless' })
})
